version: '3'
services:
        zabbix-server:
                image: zabbix/zabbix-appliance:latest
                restart: always
                ports:
                        - "10051:10051"
                        - "8080:80"
                volumes:
                        - /etc/localtime:/etc/localtime:ro
                        - /etc/timezone:/etc/timezone:ro
                        - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
                        - ./zabbix/externalscripts:/usr/lib/zabbix/externalscripts
                        - ./zabbix/modules:/var/lib/zabbix/modules
                        - ./zabbix/enc:/var/lib/zabbix/enc
                        - ./zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
                        - ./zabbix/ssl/certs:/var/lib/zabbix/ssl/certs
                        - ./zabbix/ssl/keys:/var/lib/zabbix/ssl/keys
                        - ./zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
                        - ./zabbix/snmptraps:/var/lib/zabbix/snmptraps
                        - ./zabbix/mibs:/var/lib/zabbix/mibs
